POST https://estudo-node-postgresql.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Primeiro video",
    "duration": 180
}

###

GET https://estudo-node-postgresql.onrender.com/videos

###

PUT https://estudo-node-postgresql.onrender.com/videos/3fe9d7ca-340e-4aad-9b0b-2f83c3a792ba
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Segundo video",
    "duration": 200
}

###

DELETE https://estudo-node-postgresql.onrender.com/videos/3fe9d7ca-340e-4aad-9b0b-2f83c3a792ba